title: "Terminal Ramblings"
author: "Elias"
description: "Metal, art, computer science"
permalink: /:title/
lang: "en"
excerpt_separator: <!--more-->
date_format: "%B %d, %Y — %H:%M %Z"
timezone: America/New_York

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: instagram, icon: instagram, url: "https://instagram.com/anxiousglxtch/"}
  - {title: Github, icon: github, url: "https://github.com/terminalglitch/"}
  - {title: Lastfm, icon: lastfm, url: "https://www.last.fm/user/terminalglitch"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
